export const b2bClients = [
  "el caminante",
  "el diario cafe",
  "fithub 51",
  "fithub 98",
  "humo",
  "hyh cocina",
  "hyh",
  "h&h",
  "mi madre sanducheria",
  "oveja negra",
  "tres fuegos",
  "foodology",
  "viral brands sas",
  "cafe y tapas",
  "cocina de inmigrantes",
  "la scarpetta",
  "rita bendek",
  "lau pasteleria",
  "manufacturas bee sas",
  "orlando malkun",
  "diego bustos",
  "café epoca",
  "sites groups sas.",
  "xocolata",
  "del sol sas",
];
