<template>
  <div>
    <b-button variant="dark" class="toolbox-button" @click="getProducts"
      >consumo</b-button
    >
    <table v-if="list.length > 0">
      <tr>
        <th>ingrediente</th>
        <th>total</th>
      </tr>
      <tr v-for="row in report" :key="row.ingrediente">
        <td>{{ row.ingredient }}</td>
        <td>{{ row.total }}</td>
      </tr>
    </table>
  </div>
</template>

<script>
import { getAll } from "@/firebase";
export default {
  name: "ButtonInventory",
  props: {
    objects: Array,
  },
  data() {
    return {
      list: [],
      report: [],
      ingredients: [
        ["aceite", 4.1],
        ["agua", 0.0],
        ["ajonjoli", 13.0],
        ["almidon", 4.72],
        ["avena", 4.0],
        ["azucar", 2.69],
        ["banano", 125.93],
        ["cafe", 26.0],
        ["canela", 10.0],
        ["chocolate 53%", 27.0],
        ["cocoa 16%", 21.0],
        ["harina de trigo", 1.73],
        ["harina integral", 1.92],
        ["huevos", 271.52],
        ["leche", 2.49],
        ["levadura", 6.18],
        ["margarina", 5.07],
        ["masa madre", 0.0],
        ["naranja", 251.85],
        ["oregano", 10.0],
        ["queso costeño", 11.82],
        ["sal", 0.75],
        ["semillas de chia", 19.0],
        ["semillas de girasol", 19.0],
        ["semillas de linaza", 7.0],
        ["tomillo", 10.0],
        ["uva fermentada", 9.6],
        ["zaatar", 76.0],
        ["zanahoria", 3.55],
      ],
      recipes: [
        {
          referencia: 1,
          producto: "mini masa madre:",
          categoria: "mm",
          harina: "original",
          tamaño: "mini",
          "harina de trigo": 125,
          "harina integral": "",
          "masa madre": 25,
          almidon: "",
          agua: 70,
          sal: 2.5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 2,
          producto: "pan de ajonjoli grande:",
          categoria: "mm",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": 1000.0,
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 550,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 250,
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 3,
          producto: "pan de ajonjoli mediano:",
          categoria: "mm",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 275,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 125,
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 4,
          producto: "pan de ajonjoli pequeño:",
          categoria: "mm",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 137.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 70,
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 5,
          producto: "pan de banano y semillas de girasol mediano:",
          categoria: "mm",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: 6,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": 125,
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 6,
          producto: "pan de banano y semillas de girasol pequeño:",
          categoria: "mm",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: 3,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": 70,
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 7,
          producto: "pan de banano y semillas de girasol:",
          categoria: "mm",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: 12,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": 250,
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 8,
          producto: "pan de bono paquete x12:",
          categoria: "otros",
          harina: "almidon",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": "",
          "masa madre": "",
          almidon: 250,
          agua: "",
          sal: 2.5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: 100,
          margarina: 35,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 250,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 9,
          producto: "pan de bono:",
          categoria: "otros",
          harina: "almidon",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": "",
          "masa madre": "",
          almidon: 20.8,
          agua: "",
          sal: 0.2,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: 8.3,
          margarina: 2.9,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 20.8,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 61,
          producto: "pan de bono x 6",
          categoria: "otros",
          harina: "almidon",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": "",
          "masa madre": "",
          almidon: 125,
          agua: "",
          sal: 1.3,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: 50,
          margarina: 17.5,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 125,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 10,
          producto: "pan de chocolate grande:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": 400,
          "cocoa 16%": 60,
        },
        {
          referencia: 11,
          producto: "pan de chocolate mediano:",
          categoria: "panes",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": 200,
          "cocoa 16%": 30,
        },
        {
          referencia: 12,
          producto: "pan de chocolate pequeño:",
          categoria: "panes",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": 100,
          "cocoa 16%": 15,
        },
        {
          referencia: 13,
          producto: "pan de hamburguesa integral:",
          categoria: "otros",
          harina: "integral",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": 45.8,
          "masa madre": "",
          almidon: "",
          agua: 20.8,
          sal: 0.8,
          aceite: "",
          azucar: 0.6,
          huevos: 0.2,
          levadura: 1.3,
          leche: 2,
          margarina: 2,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 14,
          producto: "pan de hamburguesa x1",
          categoria: "otros",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": 45.8,
          "harina integral": "",
          "masa madre": "",
          almidon: "",
          agua: 20.8,
          sal: 0.8,
          aceite: "",
          azucar: 0.6,
          huevos: 0.2,
          levadura: 1.3,
          leche: 2,
          margarina: 2,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 15,
          producto: "pan de masa madre mediano:",
          categoria: "panes",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 262.5,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 16,
          producto: "pan de masa madre pequeño:",
          categoria: "panes",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 131.3,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 17,
          producto: "pan de masa madre:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 525,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 18,
          producto: "pan de queso costeño grande:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 500,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 300,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 19,
          producto: "pan de queso costeño medio:",
          categoria: "panes",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 250,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 150,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 20,
          producto: "pan de queso costeño pequeño:",
          categoria: "panes",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 125,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 75,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 21,
          producto: "pan de semillas grande:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 550,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 150,
          avena: 30,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": 30,
          "semillas de girasol": 120,
          "semillas de linaza": 30,
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 22,
          producto: "pan de semillas mediano:",
          categoria: "panes",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 275,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 100,
          avena: 20,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": 20,
          "semillas de girasol": 80,
          "semillas de linaza": 20,
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 23,
          producto: "pan de semillas pequeño:",
          categoria: "panes",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 137.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 50,
          avena: 10,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": 10,
          "semillas de girasol": 40,
          "semillas de linaza": 10,
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 24,
          producto: "pan de uva grande:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 550,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": 200,
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 25,
          producto: "pan de uva mediano:",
          categoria: "panes",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 275,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": 100,
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 26,
          producto: "pan de uva pequeño:",
          categoria: "panes",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 137.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": 50,
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 27,
          producto: "pan de zaatar mediano:",
          categoria: "panes",
          harina: "original",
          tamaño: "mediano",
          "harina de trigo": 500,
          "harina integral": "",
          "masa madre": 100,
          almidon: "",
          agua: 131.3,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: 15,
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 28,
          producto: "pan de zaatar pequeño:",
          categoria: "panes",
          harina: "original",
          tamaño: "pequeño",
          "harina de trigo": 250,
          "harina integral": "",
          "masa madre": 50,
          almidon: "",
          agua: 262.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: 7,
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 29,
          producto: "pan de zaatar:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": "1,000.0",
          "harina integral": "",
          "masa madre": 200,
          almidon: "",
          agua: 525,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: 30,
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 30,
          producto: "pan focaccia :",
          categoria: "otros",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": 550,
          "harina integral": "",
          "masa madre": "",
          almidon: "",
          agua: 250,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: 15,
          leche: "",
          margarina: 24,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 31,
          producto: "pan integral de ajonjoli grande:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 250,
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 32,
          producto: "pan integral de ajonjoli mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 125,
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 33,
          producto: "pan integral de ajonjoli pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 70,
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 34,
          producto: "pan integral de chocolate grande:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": 400,
          "cocoa 16%": 60,
        },
        {
          referencia: 35,
          producto: "pan integral de chocolate mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": 200,
          "cocoa 16%": 30,
        },
        {
          referencia: 36,
          producto: "pan integral de chocolate pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": 100,
          "cocoa 16%": 15,
        },
        {
          referencia: 37,
          producto: "pan integral de queso grande:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 570,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 300,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 38,
          producto: "pan integral de queso mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 285,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 150,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 39,
          producto: "pan integral de queso pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 142.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": 75,
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 40,
          producto: "pan integral de semillas mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 325,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 100,
          avena: 20,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": 20,
          "semillas de girasol": 80,
          "semillas de linaza": 20,
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 41,
          producto: "pan integral de semillas pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 162.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 50,
          avena: 10,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": 10,
          "semillas de girasol": 40,
          "semillas de linaza": 10,
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 42,
          producto: "pan integral de semillas y banano grande:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 650,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: 12,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": 250,
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 43,
          producto: "pan integral de semillas y banano mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 325,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: 6,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": 125,
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 44,
          producto: "pan integral de semillas y banano pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 162.5,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: 3,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": 70,
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 45,
          producto: "pan integral de semillas:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 650,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: 150,
          avena: 30,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": 30,
          "semillas de girasol": 120,
          "semillas de linaza": 30,
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 46,
          producto: "pan integral de uva grande:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": 200,
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 47,
          producto: "pan integral de uva mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": 100,
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 48,
          producto: "pan integral de uva pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": 50,
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 49,
          producto: "pan integral de zaatar grande:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: 30,
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 50,
          producto: "pan integral de zaatar mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: 15,
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 51,
          producto: "pan integral de zaatar pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: 7,
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 52,
          producto: "pan integral mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: 15,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 53,
          producto: "pan integral pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: 7,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 54,
          producto: "pan integral sin avena grande :",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 600,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 55,
          producto: "pan integral sin avena mediano:",
          categoria: "panes",
          harina: "integral",
          tamaño: "mediano",
          "harina de trigo": "",
          "harina integral": 500,
          "masa madre": 100,
          almidon: "",
          agua: 300,
          sal: 10,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 56,
          producto: "pan integral sin avena pequeño:",
          categoria: "panes",
          harina: "integral",
          tamaño: "pequeño",
          "harina de trigo": "",
          "harina integral": 250,
          "masa madre": 50,
          almidon: "",
          agua: 150,
          sal: 5,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 57,
          producto: "pan integral:",
          categoria: "panes",
          harina: "integral",
          tamaño: "grande",
          "harina de trigo": "",
          "harina integral": "1,000.0",
          "masa madre": 200,
          almidon: "",
          agua: 650,
          sal: 20,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: 30,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 58,
          producto: "torta de naranja:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": 260,
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: 168,
          azucar: 327,
          huevos: 4,
          levadura: "",
          leche: "",
          margarina: 5,
          ajonjoli: "",
          avena: 30,
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: 2,
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 59,
          producto: "torta de pan con banano:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": 260,
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: 168,
          azucar: 300,
          huevos: 4,
          levadura: "",
          leche: "",
          margarina: 5,
          ajonjoli: "",
          avena: "",
          banano: 6,
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": 6,
        },
        {
          referencia: 60,
          producto: "torta de zanahoria:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": 260,
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: 168,
          azucar: 393,
          huevos: 4,
          levadura: "",
          leche: "",
          margarina: 5,
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: 1,
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: 475,
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 61,
          producto: "pan foodology:",
          categoria: "panes",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": 700,
          "harina integral": "",
          "masa madre": 140,
          almidon: "",
          agua: 368,
          sal: 14,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 62,
          producto: "deditos la jaula:",
          categoria: "panes",
          harina: "original",
          tamaño: "grande",
          "harina de trigo": 60,
          "harina integral": "",
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: 3,
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "60",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 63,
          producto: "mini torta de zanahoria:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": 16,
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: 10,
          azucar: 23,
          huevos: "0.25",
          levadura: "",
          leche: "",
          margarina: "0.3",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "0.15",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: 28,
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 64,
          producto: "mini torta de naranja:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": 22,
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: 14,
          azucar: 24,
          huevos: "0.34",
          levadura: "",
          leche: "",
          margarina: "0.41",
          ajonjoli: "",
          avena: "2.5",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "0.2",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
        {
          referencia: 65,
          producto: "mini torta de pan con banano:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": "15.3",
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: 10,
          azucar: 18,
          huevos: "0.25",
          levadura: "",
          leche: "",
          margarina: "0.33",
          ajonjoli: "",
          avena: "",
          banano: "0.35",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "0.35",
        },
        {
          referencia: 66,
          producto: "panes surtidos:",
          categoria: "tortas",
          harina: "original",
          tamaño: "unico",
          "harina de trigo": "",
          "harina integral": "750",
          "masa madre": "",
          almidon: "",
          agua: "",
          sal: "",
          aceite: "",
          azucar: "",
          huevos: "",
          levadura: "",
          leche: "",
          margarina: "",
          ajonjoli: "",
          avena: "",
          banano: "",
          cafe: "",
          canela: "",
          "queso costeño": "",
          "semillas de chia": "",
          "semillas de girasol": "",
          "semillas de linaza": "",
          naranja: "",
          "uva fermentada": "",
          zanahoria: "",
          zaatar: "",
          oregano: "",
          tomillo: "",
          "chocolate 53%": "",
          "cocoa 16%": "",
        },
      ],
    };
  },
  methods: {
    ingredientReport: function () {
      const report = [];
      this.ingredients.forEach(function (i) {
        let ingredient = i[0];
        let reportRow = { ingredient: ingredient, total: 0.0 };
        report.push(reportRow);
      });
      this.list.forEach(
        function (p) {
          if (p.recipe && p.recipe !== "00") {
            this.recipes.forEach(
              function (r) {
                if (p.recipe == r.referencia) {
                  report.forEach(
                    function (row) {
                      if (r[row.ingredient] == "") {
                        r[row.ingredient] = 0;
                      }
                      if (this.isString(r[row.ingredient])) {
                        r[row.ingredient] = parseFloat(
                          r[row.ingredient].replace(/,/g, "")
                        );
                      }
                      console.log(r.referencia);

                      console.log(parseFloat(r[row.ingredient]));
                      row.total += Math.round(r[row.ingredient] * p.quantity);
                    }.bind(this)
                  );
                }
              }.bind(this)
            );
          }
        }.bind(this)
      );

      this.report = report;
    },
    getProducts() {
      getAll("products").then((p) => {
        const nvr = {};
        p.forEach((k) => {
          nvr[k.name] = k.recipe || "00";
        });
        let namesVsRecipes = nvr;
        let products = [];
        this.objects.forEach((e) => {
          e.products.forEach((p) => {
            products.push(p);
          });
        });
        let report = {};
        products.forEach((p) => {
          let keys = Object.keys(report);
          if (keys.includes(p.name)) {
            report[p.name] = parseInt(report[p.name]) + parseInt(p.quantity);
          } else {
            report[p.name] = p.quantity;
          }
        });

        const ordered = {};
        Object.keys(report)
          .sort()
          .forEach(function (key) {
            ordered[key] = report[key];
          });

        let namesVsQuantities = ordered;
        Object.keys(namesVsQuantities).forEach((n) => {
          this.list.push({
            name: n,
            recipe: namesVsRecipes[n],
            quantity: namesVsQuantities[n],
          });
        });
        this.ingredientReport();
      });
    },
    isString(x) {
      return Object.prototype.toString.call(x) === "[object String]";
    },
  },
};
</script>

<style></style>
