[
  { name: "5 semillas mediano 25% dcto", recipe: "22", quantity: 1 },
  { name: "ajonjolí mediano 25% dcto", recipe: "3", quantity: 1 },
  { name: "chocolate pequeño 25% dcto", recipe: "12", quantity: 3 },
  { name: "chocolate pequeño 30% dcto", recipe: "12", quantity: 1 },
  { name: "domicilio", recipe: "00", quantity: 92 },
  { name: "integral y avena mediano 25% dcto", recipe: "52", quantity: 1 },
  { name: "mini masa madre", recipe: "1", quantity: "9" },
  { name: "mini torta de banano", recipe: "00", quantity: 13 },
  { name: "mini torta de naranja", recipe: "00", quantity: 6 },
  { name: "mini torta de zanahoria", recipe: "00", quantity: 12 },
  { name: "original grande", recipe: "17", quantity: 36 },
  { name: "original mediano 25% dcto", recipe: "15", quantity: 3 },
  { name: "pan 5 semillas mediano", recipe: "22", quantity: 9 },
  { name: "pan de ajonjoli grande", recipe: "2", quantity: 2 },
  { name: "pan de ajonjoli mediano", recipe: "3", quantity: 3 },
  { name: "pan de ajonjoli pequeño", recipe: "4", quantity: 1 },
  { name: "pan de banano y semillas de girasol", recipe: "7", quantity: 1 },
  {
    name: "pan de banano y semillas de girasol mediano",
    recipe: "5",
    quantity: 1,
  },
  {
    name: "pan de banano y semillas de girasol pequeño",
    recipe: "6",
    quantity: 1,
  },
  { name: "pan de bono paquete", recipe: "00", quantity: 10 },
  { name: "pan de bono x 6", recipe: "00", quantity: 3 },
  { name: "pan de chocolate mediano", recipe: "11", quantity: 6 },
  { name: "pan de chocolate pequeño", recipe: "12", quantity: 8 },
  { name: "pan de hamburguesa", recipe: "14", quantity: 102 },
  { name: "pan de hamburguesa integral", recipe: "13", quantity: "6" },
  { name: "pan de masa madre mediano", recipe: "15", quantity: 17 },
  { name: "pan de masa madre pequeño", recipe: "16", quantity: 4 },
  { name: "pan de queso costeño grande", recipe: "18", quantity: 1 },
  { name: "pan de queso costeño medio", recipe: "19", quantity: 4 },
  { name: "pan de queso costeño pequeño", recipe: "20", quantity: 1 },
  { name: "pan de semillas grande", recipe: "21", quantity: 2 },
  { name: "pan de semillas pequeño", recipe: "23", quantity: 3 },
  { name: "pan de uva mediano", recipe: "25", quantity: 2 },
  { name: "pan de zaatar mediano", recipe: "27", quantity: 3 },
  { name: "pan de zaatar pequeño", recipe: "28", quantity: "2" },
  { name: "pan integral", quantity: 4 },
  { name: "pan integral de ajonjoli mediano", recipe: "32", quantity: 1 },
  { name: "pan integral de queso mediano", recipe: "38", quantity: 1 },
  { name: "pan integral de semillas", recipe: "45", quantity: 1 },
  { name: "pan integral de semillas mediano", recipe: "40", quantity: 1 },
  { name: "pan integral de semillas pequeño", recipe: "41", quantity: 2 },
  {
    name: "pan integral de semillas y banano mediano",
    recipe: "43",
    quantity: 1,
  },
  { name: "pan integral de uva pequeño", recipe: "48", quantity: 1 },
  { name: "pan integral de zaatar grande", recipe: "49", quantity: 1 },
  { name: "pan integral de zaatar mediano", recipe: "50", quantity: "1" },
  { name: "pan integral mediano", recipe: "52", quantity: 9 },
  { name: "pan integral pequeño", recipe: "53", quantity: 1 },
  { name: "pan integral sin avena grande", recipe: "54", quantity: 2 },
  { name: "pan integral sin avena mediano", recipe: "55", quantity: 4 },
  { name: "pan integral sin avena pequeno", recipe: "56", quantity: 1 },
  { name: "pan sin gluten x 6", recipe: "00", quantity: 4 },
  { name: "panes surtidos", recipe: "00", quantity: 3 },
  { name: "queso mediano 25% dcto", recipe: "19", quantity: 2 },
  { name: "queso mediano 30% dcto", recipe: "19", quantity: 1 },
  { name: "queso pequeño 25% dcto", recipe: "20", quantity: 1 },
  { name: "torta de naranja", recipe: "58", quantity: 1 },
  { name: "uva mediano 25% dcto", recipe: "27", quantity: 1 },
  { name: "zaatar mediano 25% dcto", recipe: "27", quantity: 1 },
  { name: "zaatar mediano 30% dcto", recipe: "27", quantity: 1 },
];
