export const JSON = [
  {
    Nombre: "Adriana Martin",
    Telefono: "313 4331009",
    Direccion: "car 57 # 82 61",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Adriana Velez",
    Telefono: "320 5035179",
    Direccion: "cra 59 # 79 142",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Alba Paternina",
    Telefono: "315 7223744",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Alberto Salgado",
    Telefono: 3152574690,
    Direccion: "car 57 # 82 61",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Alejandro Aguilar",
    Telefono: "316 8747665",
    Direccion: "Cra 64 b no. 86 - 116 apto 604",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Alejandro Vasquez",
    Telefono: "310 6243972",
    Direccion: "cra 56 # 80 - 81 apto 18",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Alexandra Sierra",
    Telefono: "318 5568878",
    Direccion: "calle 57 # 36 - 31",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "nutricionista que quiere ayudarnos",
  },
  {
    Nombre: "Alexandra Vives",
    Telefono: 3153335429,
    Direccion: "cra 59b #85-64",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2000-08-04",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad: "le gusta el pan masa madre 100% integral con avena",
  },
  {
    Nombre: "Alfonso Manzano",
    Telefono: 3206618237,
    Direccion: "cra 52b#96-68 edf. dublin apto 603b",
    Correo: "",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-12-07",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Alma Perez",
    Telefono: 3146691402,
    Direccion: "calle 79 # 49c - 38 local 1",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-02-08",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Amalin Hazbun",
    Telefono: 3008152634,
    Direccion: "cra 64b # 94 -128",
    Correo: "",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-02-25",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Ana María Badel",
    Telefono: "318 3123538",
    Direccion: "Calle 94 no 57-57 piso 1",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Ana Maria Diepa",
    Telefono: "314 5160890",
    Direccion: "Cra 56 no 80-81. Apto 9",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Ana María Slevi",
    Telefono: 3135097150,
    Direccion: "caujaral lote 13 calle del no me olvides casa reinaldo slevi",
    Correo: "",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-08-17",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad:
      "hace parte de un grupo de mujeres q viven en el caujaral y compran en conjunto para llevar.",
  },
  {
    Nombre: "Ana Maria Zuñiga",
    Telefono: 3013041252,
    Direccion: "cra 57 # 84 -155 apto 4b edf. Odessa",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-28",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad: "le gusta el pan masa madre 100% integral con avena",
  },
  {
    Nombre: "Andrea Cure",
    Telefono: "312 6396304",
    Direccion: "Rappi",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Andrea Kopp",
    Telefono: 3157559805,
    Direccion: "cra 64c # 84 - 132",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad:
      "su papa compra pan fresco todos los dias en la baguette a las 7 de la manana, bacano ver si podemos ahorrarle la salida y q le llegue a lacasa",
  },
  {
    Nombre: "Andrea Saieh",
    Telefono: 3226066831,
    Direccion: "cra 52b # 94 - 229 domenico 52 apto 304",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-08-09",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Andres Perez",
    Telefono: "320 5328571",
    Direccion: "Viene por su pan",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Andres Ribbon",
    Telefono: "301 7698196",
    Direccion: "cra 62#76-95 bloq 9 apto 301",
    Correo: "andyribont@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Andrés Santiago",
    Telefono: 3205315479,
    Direccion: "cra 56 # 84 -101",
    Correo: "",
    "Ultima vez hablado": "2/17/2020",
    "Hablar el": "",
    Cumpleanos: "2020-03-11",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Andres Vergara",
    Telefono: "304 3804549",
    Direccion: "Cra 51b # 79 - 185",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Andri Kotzee",
    Telefono: "instagram, no logre ponerme en contacto con el o ella",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Angie Choperena",
    Telefono: 3135742713,
    Direccion: "calle 78 # 57 - 95",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-10-14",
    Elección: "queso",
    "De Donde Vienen": "amiga madre",
    Particularidad: "le encanta la torta de zanahoria",
  },
  {
    Nombre: "Angie Choperena",
    Telefono: "313 5742713",
    Direccion: "Calle 78# 57-95 edificio Turqueza Real apto 201",
    Correo: "Angelachoperena@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Antonio Celia",
    Telefono: "310 3622277",
    Direccion: "car 58 # 84 185",
    Correo: "antonio_celia@me.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Antonio Lewis",
    Telefono: "1 (404) 558-1737",
    Direccion: "Carrera 64C # 84 - 260 Apartamento 602",
    Correo: "no lo dio",
    "Ultima vez hablado": "28 abril",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Antonio Santiago",
    Telefono: "320 5419546",
    Direccion: "cra 56 # 84 - 101",
    Correo: "asantiagop2@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Antonio Zabarain",
    Telefono: "310 6468453",
    Direccion: "Carrera 55 número 80 - 56",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Anuar Perez",
    Telefono: "304 6761624",
    Direccion: "no vive en b/quilla",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Astrid Puccini",
    Telefono: "300 2611069",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Aura Lopez",
    Telefono: "301 6391340",
    Direccion: "K 56 75 20",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Beatrice Matera",
    Telefono: "304 5465765",
    Direccion: "Calle 85#52-27",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Blanca Dolly Giraldo",
    Telefono: 3103529733,
    Direccion: "cra 59b # 90 - 45 edf. Marquez de Riomar PH 1101 Torre A",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Brenda Borges",
    Telefono: "318 2695699",
    Direccion: "calle 10 # 12 - 35",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
  },
  {
    Nombre: "Camila Boudez",
    Telefono: 3008054262,
    Direccion: "cra 64b # 86 - 141 edf. Coral",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-07-13",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Camilo Gonzales",
    Telefono: "302 3906589",
    Direccion: "Cra 57 n 82-52",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Carlo Acevedo",
    Telefono: 3116600130,
    Direccion: "calle 90 # 58 - 51 apto 701",
    Correo: "",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-06-27",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Carlos Alberto Salgado",
    Telefono: "315 5433505",
    Direccion: "car 57 # 85 85",
    Correo: "casalgado@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "2000-12-02",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Carlos De Las Aguas",
    Telefono: 3145706453,
    Direccion: "no quiso darla",
    Correo: "Elicahelta4@hotmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Carlos Murgas",
    Telefono: 3105533598,
    Direccion: "cra 58#64-82",
    Correo: "cjmurgas@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Carolina Correa",
    Telefono: "321 4685287",
    Direccion: "calle 7 No 13 - 57",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
  },
  {
    Nombre: "Catalina Suarez",
    Telefono: "313 2933130",
    Direccion: "Urbanizacion Caujaral casa 7. La casa de gabriel rosales",
    Correo: "catalinasuarezperez@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "2000-05-14",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Clara Calle",
    Telefono: 3155010026,
    Direccion: "cra 64b # 91 - 96 casa 4",
    Correo: "claracalle@gmail.com",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-07-13",
    Elección: "queso",
    "De Donde Vienen": "amiga madre",
    Particularidad: "",
  },
  {
    Nombre: "Clara Vargas",
    Telefono: "310 6477694",
    Direccion: "Conjunto Maitta Casa 3",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
  },
  {
    Nombre: "Cuchi Salcedo",
    Telefono: 3016276795,
    Direccion: "cra 56 No. 84-90 Apto 4B",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "le gusta tener pan en la casa",
  },
  {
    Nombre: "Daniel Castañeda",
    Telefono: 3016167918,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Daniela Guerrero",
    Telefono: 3043818847,
    Direccion: "calle 78 # 57 - 95 edf Turquesa real apto 702",
    Correo: "",
    "Ultima vez hablado": "4/Mar/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-24",
    Elección: "queso",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Daniela Pabon",
    Telefono: 3145958040,
    Direccion: "cra 56 # 84 - 90 apto 6 a",
    Correo: "",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-02",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Daniella Jaramillo",
    Telefono: "321 6989125",
    Direccion: "cra 56 # 80 - 275 apto 9b",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Danilo Acosta",
    Telefono: "315 7077203",
    Direccion: "cra 43b no 90-93 apto 605",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "David Escaf",
    Telefono: 3008167074,
    Direccion: "calle 83 # 42d - 123 apto 804",
    Correo: "",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-12-13",
    Elección: "queso",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "David Montero",
    Telefono: 3126981356,
    Direccion: "cra 55 # 82 - 72 apto 1005 soho 55 # 2",
    Correo: "davidmonterojalil@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amigo david",
    Particularidad: "",
  },
  {
    Nombre: "Diana Paternina",
    Telefono: 3157449664,
    Direccion: "manda por sus panes",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Diego Mariño",
    Telefono: "311 6955301",
    Direccion: "Cra 21 a # 14 pto col",
    Correo: "Dmarinol@hotmail.com",
    "Ultima vez hablado": "22 diciembre",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Dimas Bauza",
    Telefono: 3003502938,
    Direccion: "cra 51 # 98 - 300",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Elena Carriazo",
    Telefono: 3157226071,
    Direccion: "caujaral",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Elizabeth Pardo",
    Telefono: 3043976575,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Elvirita",
    Telefono: 3017758011,
    Direccion: "cra 57 # 77 - 53 apto 504 edf Alessandra",
    Correo: "",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-02-18",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Esteban Henao",
    Telefono: 3117770849,
    Direccion: "cra 52 # 106 - 213 edf Oceana 52 apto 1510",
    Correo: "",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-10-17",
    Elección: "zaatar",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Ethna Elizondo",
    Telefono: 3008441868,
    Direccion: "calle 78 # 57 - 135 apto 4a",
    Correo: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-11-04",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Eugenia Escaff",
    Telefono: 3134775058,
    Direccion: "cra 55 # 82 - 181 apto 802 edf Antonella",
    Correo: "",
    "Ultima vez hablado": "28/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-03-04",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Ezequiel Davila",
    Telefono: "320 5435138",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Faride Rocha",
    Telefono: 3235673692,
    Direccion: "cra 50 103 - 24 casa 2 villa santos",
    Correo: "",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "cualquiera",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Felipe Echeverri",
    Telefono: "310 4277160",
    Direccion: "pto colombia",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Francesca Mancini",
    Telefono: "312 6230666",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Francisco Guerra",
    Telefono: "315 7522203",
    Direccion: "Cra 56#84-90 edif. Guayaba. Apto. 4b",
    Correo: "Pacoguerran@gmail.com",
    "Ultima vez hablado": "11 de septiembre",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Gabriel Delgado",
    Telefono: "310 6302672",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Gabriel Obyrne",
    Telefono: "301 5051294",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Gisela Madrigales",
    Telefono: "320 5236468",
    Direccion:
      "transversal 44 nro 102-80 apartamento 1422 Torre 07 conjunto Olivenza",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Hernando Cotes",
    Telefono: 3135717177,
    Direccion: "calle 78 # 57 - 115 apto 2 edf Lamas",
    Correo: "",
    "Ultima vez hablado": "29/Feb/2020",
    "Hablar el": "7 de marzo",
    Cumpleanos: "2020-04-21",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Ingrid Saad",
    Telefono: 3157306969,
    Direccion: "Cra 51 # 79-155 apto 202",
    Correo: "Iss09@hotmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Isabela El Caminante",
    Telefono: 3002836109,
    Direccion: "cra 64 # 68 - 36 edf. Parques Cisneros apto 401",
    Correo: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Isha Osorio",
    Telefono: "300 6307214",
    Direccion: "calle 5 # 13 - 460",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
  },
  {
    Nombre: "Joan Velazquez",
    Telefono: 3185744298,
    Direccion: "cra 50 # 98 - 40 casa 8 Castilla Vieja",
    Correo: "",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-04-24",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Jorge Pacheco",
    Telefono: "300 5207704",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Juan Camilo Olmos",
    Telefono: 3163656256,
    Direccion: "cra 58 # 64 - 264 edf Geranios de Malva apt 4a",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Juan Cediel",
    Telefono: "313 5861370",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "juan correa",
    Telefono: "300 7026695",
    Direccion: "Kra 57#77-24 apto 4f",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Juan P Zambrano",
    Telefono: "314 5336771",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Juliana Restrepo",
    Telefono: "313 5404770",
    Direccion: "cra 51 # 79 - 81 apt 701",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Katia Navarro",
    Telefono: "310 4619738",
    Direccion: "calle 99 # 58 - 99",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Kelly Chico",
    Telefono: 3022796765,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "queso",
    "De Donde Vienen": "tres fuegos",
    Particularidad: "hay que estar pendiente de sus pedidos",
  },
  {
    Nombre: "Kelly Pozo",
    Telefono: "300 2930826",
    Direccion: "calle 53 # 52 - 68 apt 504f",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Leo Barrios",
    Telefono: 3013745727,
    Direccion: "cra 59 # 68 - 117 apt 303A edf Condado del Prado",
    Correo: "",
    "Ultima vez hablado": "6/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-01-18",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Libia de Sojo",
    Telefono: "310 6304646",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Lina Orozco",
    Telefono: "300 4722351",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Lina Urueta",
    Telefono: "313 7427827",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Lucia Martinez",
    Telefono: "320 5423636",
    Direccion: "Manzana 1 Lote 22 Casa de Nestor Bottia",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
  },
  {
    Nombre: "Luis Escobar",
    Telefono: "313 5043407",
    Direccion: "",
    Correo: "Luisgescobar@gmail.com",
    "Ultima vez hablado": "Marzo 9",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Luis Mora",
    Telefono: "300 8161258",
    Direccion: "el manda un rappi",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Lupe Abuchaible",
    Telefono: "1(786) 371-1574",
    Direccion: "cra 57 # 84 - 53",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Mabel Guerra De Vives",
    Telefono: 3135121476,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Mafe Torres",
    Telefono: "301 3250678",
    Direccion: "car 50 # 76 - 180",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instragram",
    Particularidad: "",
  },
  {
    Nombre: "Marcela Blanco",
    Telefono: "315 7165195",
    Direccion: "Car 56 # 79 - 276 piso 2",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "le gusta solo la harina integral",
  },
  {
    Nombre: "Marcela Emilia",
    Telefono: 3008157656,
    Direccion: "cra 58 # 81 - 160 apto 8",
    Correo: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-02-02",
    Elección: "cualquiera",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Marcela Olarte",
    Telefono: "315 5564962",
    Direccion: "Cra 50 #61-116",
    Correo: "marce.og24@hotmail.com",
    "Ultima vez hablado": "no lo dio jajaj",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Margarita Ceballos",
    Telefono: "314 5935750",
    Direccion: "Villa Campestre av los cocos waikiki casa 3",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Margarita Marquez",
    Telefono: "315 7222256",
    Direccion: "Cra 57#68-156 apto 6B",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "María Alejandra Kaled",
    Telefono: 3022270555,
    Direccion: "cra 50 # 107 - 110",
    Correo: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-10-22",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Maria Carolina Osorio",
    Telefono: 3116881565,
    Direccion: "cra 58 # 82 - 40",
    Correo: "",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-09-26",
    Elección: "zaatar",
    "De Donde Vienen": "eventos",
    Particularidad: "",
  },
  {
    Nombre: "Maria cecilia Donado",
    Telefono: "320 5931666",
    Direccion: "car 57 # 82 - 61",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Maria Elvira De Cuello",
    Telefono: 3157226946,
    Direccion: "cra 51b # 79 - 185",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Maria Eugenia Martelo",
    Telefono: "312 6703700",
    Direccion: "cra 59 # 84 77",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "Geña martelo",
  },
  {
    Nombre: "Maria Eugenia Peña",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Maria Eugenia Samur",
    Telefono: 3157232343,
    Direccion: "cra 58 # 79 - 295 edf Acqualina apt 10b",
    Correo: "",
    "Ultima vez hablado": "6/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-25",
    Elección: "cualquiera",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Maria Isabella Shmulson",
    Telefono: "310 7003333",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Maria Majami",
    Telefono: 3156251098,
    Direccion: "cra 52 # 82 - 234 edf Loft 82 apt 402",
    Correo: "",
    "Ultima vez hablado": "27/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-12-08",
    Elección: "zaatar",
    "De Donde Vienen": "instagram",
    Particularidad: "compro pan sin sal para su bebe de un año, le encanto.",
  },
  {
    Nombre: "Maria Patricia Cotes",
    Telefono: 3186966985,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-11-29",
    Elección: "queso",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Maria Patricia Salcedo",
    Telefono: "no tenemo el numero",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "María Paula Dangon",
    Telefono: 3008102961,
    Direccion: "calle 83 # 42d - 123 edf Romero y Loto",
    Correo: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-10-01",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Mariana Gonzales",
    Telefono: 3006307213,
    Direccion: "cra 57 # 77 - 24 edf Las Trinitarias apt 4f",
    Correo: "",
    "Ultima vez hablado": "26/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-20",
    Elección: "queso costeño",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Marina Davila",
    Telefono: "no tenemo el numero",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Marta Acevedo",
    Telefono: 3186979777,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Mary Castro",
    Telefono: "no tenemo el numero",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Merce Botero",
    Telefono: "300 8143132",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Merci Lopez",
    Telefono: "no tenemo el numero",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Mitch Olmos",
    Telefono: 3153405731,
    Direccion: "cra 56 # 82 - 174 apt 903",
    Correo: "",
    "Ultima vez hablado": "4/Mar/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-06",
    Elección: "queso costeño",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Monica De Jaramillo",
    Telefono: 3106315973,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Monica Mercado",
    Telefono: "350 7680206",
    Direccion: "cra 42c # 83 - 99",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
  },
  {
    Nombre: "Monica Urquijo",
    Telefono: "301 5355933",
    Direccion: "carrera 52 # 82 - 203",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "2020-01-18",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Natalia Zuleta",
    Telefono: "305 7455669",
    Direccion: "car 56 # 82 - 172",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Nestor Barrios",
    Telefono: 3008879473,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Nicole Hill",
    Telefono: 3145870381,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Olga De Loewy",
    Telefono: 3205422132,
    Direccion: "cra 13 # 5 - 66 lagos del caujaral",
    Correo: "",
    "Ultima vez hablado": "8/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-03-30",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Ornella Grosso",
    Telefono: "310 3679324",
    Direccion: "car 57 # 84 - 173",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Owen Jones",
    Telefono: 3116592464,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "no ha contestado",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Pablo Bustillo",
    Telefono: 3165856916,
    Direccion: "Calle 75 # 54 80",
    Correo: "pablobs1@yahoo.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Pao Rodriguez",
    Telefono: 3135648883,
    Direccion: "cra 36 # 63b esquina triple a recreo ext 318",
    Correo: "",
    "Ultima vez hablado": "28/Feb/20",
    "Hablar el": "07/Mar/2020",
    Cumpleanos: "2020-11-27",
    Elección: "queso",
    "De Donde Vienen": "instagram",
    Particularidad: "",
  },
  {
    Nombre: "Paola Acuña",
    Telefono: 3046562174,
    Direccion: "cra 52b # 94 - 47",
    Correo: "",
    "Ultima vez hablado": "11/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-11-03",
    Elección: "queso",
    "De Donde Vienen": "evento",
    Particularidad: "",
  },
  {
    Nombre: "Patricia maestre",
    Telefono: "320 5659880",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Paula Patiño",
    Telefono: "318 7901185",
    Direccion: "calle 99 # 58 - 112",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Paula Urdaneta",
    Telefono: "300 8141441",
    Direccion: "cra 52 # 82 - 202 apto 6a",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Pia Monor",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Pipe Matera",
    Telefono: "317 3661671",
    Direccion: "Calle78#57-50   apt 2a",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Ray Bravo",
    Telefono: "321 5411331",
    Direccion: "Calle 96 # 57-19",
    Correo: "Raybravog@gmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Ricardo Lapeira",
    Telefono: "301 6424322",
    Direccion: "Carrera 59c #81-73",
    Correo: "ralt46@gmail.com",
    "Ultima vez hablado": "Diciembre 5",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Roberto Caridi",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Roberto Cuello",
    Telefono: "316 5248764",
    Direccion: "cra 52 # 82 - 161 apto 2b",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Rochy Moreno",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Rodolfo Schmulson",
    Telefono: 3157212121,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Rosa Paternina",
    Telefono: "320 5314286",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Rose Khbeis",
    Telefono: 3015554683,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Roxana Capella",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Sara Mendoza",
    Telefono: "317 4345441",
    Direccion: "Cra. 47 # 102 - 170  Apto. 1005 - Torre 2",
    Correo: "saramendoza87@gmail.com",
    "Ultima vez hablado": "6 de Septiembre",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Sebastian Gonzlaes",
    Telefono: "300 5101568",
    Direccion: "Calle 92 N 71A -90\nEdificio springfield, apto 704 torre E",
    Correo: "Sebgonzalezb@gmail.com",
    "Ultima vez hablado": "4 diciembre",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Sebastian Otalora",
    Telefono: "315 6684264",
    Direccion: "cra 65 # 81b - 17",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "sanducheria barbaros",
  },
  {
    Nombre: "Shadia Cure",
    Telefono: "52 1 55 1938 3195",
    Direccion: "Calle 77 # 55-91",
    Correo: "scure04@hotmail.com",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Silvana Maria",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Silvia Aguilera",
    Telefono: "310 6325743",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "caujaral",
  },
  {
    Nombre: "Stella Forero",
    Telefono: "310 6320100",
    Direccion: "Cra 57#81-77 Apto#3 Edificio Villa Aleida",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Stephanie Otero",
    Telefono: "323 4925295",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Tania Jassit",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Tata",
    Telefono: "315 5429993",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Tatiana Charris",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Traice Biggs",
    Telefono: 3135741437,
    Direccion: "cra 52b # 100 - 240",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
  },
  {
    Nombre: "Valentina Riascos",
    Telefono: 3108978061,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "Valerie Hazbun",
    Telefono: 3216652703,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Veronica Duarte",
    Telefono: 3205213683,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "Vianny Galan",
    Telefono: "318 5222621",
    Direccion: "calle 60 # 44-72",
    Correo: "vgalan@glowangels.co",
    "Ultima vez hablado": "3 de enero",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Vicky Cabrera",
    Telefono: "",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
  {
    Nombre: "Vicky Garcia",
    Telefono: 3157225523,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
  },
  {
    Nombre: "VIcky Marquez",
    Telefono: "310 6301785",
    Direccion: "car 56 # 80 - 81 apto 7",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Viri Amiga De Vicky",
    Telefono: 3007572132,
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
  },
  {
    Nombre: "Wicho Jose Escaf",
    Telefono: 3187071815,
    Direccion: "cra 57 # 96 - 38 apt 2c",
    Correo: "",
    "Ultima vez hablado": "29/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-05-10",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
  },
  {
    Nombre: "William Salgado",
    Telefono: "317 5157944",
    Direccion: "",
    Correo: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
  },
];
