export const JSON = [
  {
    Nombre: "Adriana Velez",
    Telefono: "320 5035179",
    Direccion: "cra 59 # 79 142",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Alejandro Vasquez",
    Telefono: "310 6243972",
    Direccion: "cra 56 # 80 - 81 apto 18",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Alexandra Sierra",
    Telefono: "318 5568878",
    Direccion: "calle 57 # 36 - 31",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "nutricionista que quiere ayudarnos",
    Correo: "",
  },
  {
    Nombre: "Alexandra Vives",
    Telefono: 3153335429,
    Direccion: "cra 59b #85-64",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2000-08-04",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad: "le gusta el pan masa madre 100% integral con avena",
    Correo: "",
  },
  {
    Nombre: "Alfonso Manzano",
    Telefono: 3206618237,
    Direccion: "cra 52b#96-68 edf. dublin apto 603b",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-12-07",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Alma Perez",
    Telefono: 3146691402,
    Direccion: "calle 79 # 49c - 38 local 1",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-02-08",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Amalin Hazbun",
    Telefono: 3008152634,
    Direccion: "cra 64b # 94 -128",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-02-25",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Ana María Slevi",
    Telefono: 3135097150,
    Direccion: "caujaral lote 13 calle del no me olvides casa reinaldo slevi",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-08-17",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad:
      "hace parte de un grupo de mujeres q viven en el caujaral y compran en conjunto para llevar.",
    Correo: "",
  },
  {
    Nombre: "Ana Maria Zuñiga",
    Telefono: 3013041252,
    Direccion: "cra 57 # 84 -155 apto 4b edf. Odessa",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-28",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad: "le gusta el pan masa madre 100% integral con avena",
    Correo: "",
  },
  {
    Nombre: "Andrea Kopp",
    Telefono: 3157559805,
    Direccion: "cra 64c # 84 - 132",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad:
      "su papa compra pan fresco todos los dias en la baguette a las 7 de la manana, bacano ver si podemos ahorrarle la salida y q le llegue a lacasa",
    Correo: "",
  },
  {
    Nombre: "Andrea Saieh",
    Telefono: 3226066831,
    Direccion: "cra 52b # 94 - 229 domenico 52 apto 304",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-08-09",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Andrés Santiago",
    Telefono: 3205315479,
    Direccion: "cra 56 # 84 -101",
    "Ultima vez hablado": "2/17/2020",
    "Hablar el": "",
    Cumpleanos: "2020-03-11",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Angie Choperena",
    Telefono: 3135742713,
    Direccion: "calle 78 # 57 - 95",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-10-14",
    Elección: "queso",
    "De Donde Vienen": "amiga madre",
    Particularidad: "le encanta la torta de zanahoria",
    Correo: "",
  },
  {
    Nombre: "Blanca Dolly Giraldo",
    Telefono: 3103529733,
    Direccion: "cra 59b # 90 - 45 edf. Marquez de Riomar PH 1101 Torre A",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Brenda Borges",
    Telefono: "318 2695699",
    Direccion: "calle 10 # 12 - 35",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
    Correo: "",
  },
  {
    Nombre: "Camila Boudez",
    Telefono: 3008054262,
    Direccion: "cra 64b # 86 - 141 edf. Coral",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-07-13",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Carlo Acevedo",
    Telefono: 3116600130,
    Direccion: "calle 90 # 58 - 51 apto 701",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-06-27",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Carlos De Las Aguas",
    Telefono: 3145706453,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Carlos Murgas",
    Telefono: 3105533598,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Carolina Correa",
    Telefono: "321 4685287",
    Direccion: "calle 7 No 13 - 57",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
    Correo: "",
  },
  {
    Nombre: "Clara Calle",
    Telefono: 3155010026,
    Direccion: "cra 64b # 91 - 96 casa 4",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-07-13",
    Elección: "queso",
    "De Donde Vienen": "amiga madre",
    Particularidad: "",
    Correo: "claracalle@gmail.com",
  },
  {
    Nombre: "Clara Vargas",
    Telefono: "310 6477694",
    Direccion: "Conjunto Maitta Casa 3",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
    Correo: "",
  },
  {
    Nombre: "Cuchi Salcedo",
    Telefono: 3016276795,
    Direccion: "cra 56 No. 84-90 Apto 4B",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "le gusta tener pan en la casa",
    Correo: "",
  },
  {
    Nombre: "Daniel Castañeda",
    Telefono: 3016167918,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Daniela Guerrero",
    Telefono: 3043818847,
    Direccion: "calle 78 # 57 - 95 edf Turquesa real apto 702",
    "Ultima vez hablado": "4/Mar/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-24",
    Elección: "queso",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Daniela Pabon",
    Telefono: 3145958040,
    Direccion: "cra 56 # 84 - 90 apto 6 a",
    "Ultima vez hablado": "19/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-02",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Daniella Jaramillo",
    Telefono: "321 6989125",
    Direccion: "cra 56 # 80 - 275 apto 9b",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "David Escaf",
    Telefono: 3008167074,
    Direccion: "calle 83 # 42d - 123 apto 804",
    "Ultima vez hablado": "17/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-12-13",
    Elección: "queso",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "David Montero",
    Telefono: 3126981356,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amigo david",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Diana Paternina",
    Telefono: 3157449664,
    Direccion: "manda por sus panes",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Dimas Bauza",
    Telefono: 3003502938,
    Direccion: "cra 51 # 98 - 300",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Elena Carriazo",
    Telefono: 3157226071,
    Direccion: "caujaral",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Elizabeth Pardo",
    Telefono: 3043976575,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Elvirita",
    Telefono: 3017758011,
    Direccion: "cra 57 # 77 - 53 apto 504 edf Alessandra",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-02-18",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Esteban Henao",
    Telefono: 3117770849,
    Direccion: "cra 52 # 106 - 213 edf Oceana 52 apto 1510",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-10-17",
    Elección: "zaatar",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Ethna Elizondo",
    Telefono: 3008441868,
    Direccion: "calle 78 # 57 - 135 apto 4a",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-11-04",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Eugenia Escaff",
    Telefono: 3134775058,
    Direccion: "cra 55 # 82 - 181 apto 802 edf Antonella",
    "Ultima vez hablado": "28/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-03-04",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Faride Rocha",
    Telefono: 3235673692,
    Direccion: "cra 50 103 - 24 casa 2 villa santos",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "cualquiera",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Francisco Guerra",
    Telefono: 3157522203,
    Direccion: "cra 56 # 84 - 90 apto 4b",
    "Ultima vez hablado": "28/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-11",
    Elección: "zaatar",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Hernando Cotes",
    Telefono: 3135717177,
    Direccion: "calle 78 # 57 - 115 apto 2 edf Lamas",
    "Ultima vez hablado": "29/Feb/2020",
    "Hablar el": "7 de marzo",
    Cumpleanos: "2020-04-21",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Isabela El Caminante",
    Telefono: 3002836109,
    Direccion: "cra 64 # 68 - 36 edf. Parques Cisneros apto 401",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "zaatar",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Isha Osorio",
    Telefono: "300 6307214",
    Direccion: "calle 5 # 13 - 460",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
    Correo: "",
  },
  {
    Nombre: "Joan Velazquez",
    Telefono: 3185744298,
    Direccion: "cra 50 # 98 - 40 casa 8 Castilla Vieja",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-04-24",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Juan Camilo Olmos",
    Telefono: 3163656256,
    Direccion: "cra 58 # 64 - 264 edf Geranios de Malva apt 4a",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Juliana Restrepo",
    Telefono: "313 5404770",
    Direccion: "cra 51 # 79 - 81 apt 701",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Katia Navarro",
    Telefono: "310 4619738",
    Direccion: "calle 99 # 58 - 99",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Kelly Chico",
    Telefono: 3022796765,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "queso",
    "De Donde Vienen": "tres fuegos",
    Particularidad: "hay que estar pendiente de sus pedidos",
    Correo: "",
  },
  {
    Nombre: "Kelly Pozo",
    Telefono: "300 2930826",
    Direccion: "calle 53 # 52 - 68 apt 504f",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Leo Barrios",
    Telefono: 3013745727,
    Direccion: "cra 59 # 68 - 117 apt 303A edf Condado del Prado",
    "Ultima vez hablado": "6/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-01-18",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Lucia Martinez",
    Telefono: "320 5423636",
    Direccion: "Manzana 1 Lote 22 Casa de Nestor Bottia",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
    Correo: "",
  },
  {
    Nombre: "Lupe Abuchaible",
    Telefono: "1(786) 371-1574",
    Direccion: "cra 57 # 84 - 53",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Mabel Guerra De Vives",
    Telefono: 3135121476,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Mafe Torres",
    Telefono: "301 3250678",
    Direccion: "car 50 # 76 - 180",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instragram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Marcela Blanco",
    Telefono: "315 7165195",
    Direccion: "Car 56 # 79 - 276 piso 2",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "le gusta solo la harina integral",
    Correo: "",
  },
  {
    Nombre: "Marcela Emilia",
    Telefono: 3008157656,
    Direccion: "cra 58 # 81 - 160 apto 8",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-02-02",
    Elección: "cualquiera",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Margarita Ceballos",
    Telefono: "314 5935750",
    Direccion: "Villa Campestre av los cocos waikiki casa 3",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "María Alejandra Kaled",
    Telefono: 3022270555,
    Direccion: "cra 50 # 107 - 110",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-10-22",
    Elección: "queso",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria Carolina Osorio",
    Telefono: 3116881565,
    Direccion: "cra 58 # 82 - 40",
    "Ultima vez hablado": "25/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-09-26",
    Elección: "zaatar",
    "De Donde Vienen": "eventos",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria cecilia Donado",
    Telefono: "320 5931666",
    Direccion: "car 57 # 82 - 61",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria Elvira De Cuello",
    Telefono: 3157226946,
    Direccion: "cra 51b # 79 - 185",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria Eugenia Peña",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria Eugenia Samur",
    Telefono: 3157232343,
    Direccion: "cra 58 # 79 - 295 edf Acqualina apt 10b",
    "Ultima vez hablado": "6/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-25",
    Elección: "cualquiera",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria Majami",
    Telefono: 3156251098,
    Direccion: "cra 52 # 82 - 234 edf Loft 82 apt 402",
    "Ultima vez hablado": "27/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-12-08",
    Elección: "zaatar",
    "De Donde Vienen": "instagram",
    Particularidad: "compro pan sin sal para su bebe de un año, le encanto.",
    Correo: "",
  },
  {
    Nombre: "Maria Patricia Cotes",
    Telefono: 3186966985,
    Direccion: "",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-11-29",
    Elección: "queso",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Maria Patricia Salcedo",
    Telefono: "no tenemo el numero",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "María Paula Dangon",
    Telefono: 3008102961,
    Direccion: "calle 83 # 42d - 123 edf Romero y Loto",
    "Ultima vez hablado": "26/Feb/20",
    "Hablar el": "",
    Cumpleanos: "2020-10-01",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Mariana Gonzales",
    Telefono: 3006307213,
    Direccion: "cra 57 # 77 - 24 edf Las Trinitarias apt 4f",
    "Ultima vez hablado": "26/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-20",
    Elección: "queso costeño",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Marina Davila",
    Telefono: "no tenemo el numero",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Marta Acevedo",
    Telefono: 3186979777,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Mary Castro",
    Telefono: "no tenemo el numero",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Merci Lopez",
    Telefono: "no tenemo el numero",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Mitch Olmos",
    Telefono: 3153405731,
    Direccion: "cra 56 # 82 - 174 apt 903",
    "Ultima vez hablado": "4/Mar/2020",
    "Hablar el": "",
    Cumpleanos: "2020-09-06",
    Elección: "queso costeño",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Monica De Jaramillo",
    Telefono: 3106315973,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Monica Mercado",
    Telefono: "350 7680206",
    Direccion: "cra 42c # 83 - 99",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "Caujaral",
    Correo: "",
  },
  {
    Nombre: "Monica Urquijo",
    Telefono: "301 5355933",
    Direccion: "carrera 52 # 82 - 203",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "2020-01-18",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Natalia Zuleta",
    Telefono: "305 7455669",
    Direccion: "car 56 # 82 - 172",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Nestor Barrios",
    Telefono: 3008879473,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Nicole Hill",
    Telefono: 3145870381,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Olga De Loewy",
    Telefono: 3205422132,
    Direccion: "cra 13 # 5 - 66 lagos del caujaral",
    "Ultima vez hablado": "8/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-03-30",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Ornella Grosso",
    Telefono: "310 3679324",
    Direccion: "car 57 # 84 - 173",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Owen Jones",
    Telefono: 3116592464,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "no ha contestado",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Pao Rodriguez",
    Telefono: 3135648883,
    Direccion: "cra 36 # 63b esquina triple a recreo ext 318",
    "Ultima vez hablado": "28/Feb/20",
    "Hablar el": "07/Mar/2020",
    Cumpleanos: "2020-11-27",
    Elección: "queso",
    "De Donde Vienen": "instagram",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Paola Acuña",
    Telefono: 3046562174,
    Direccion: "cra 52b # 94 - 47",
    "Ultima vez hablado": "11/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-11-03",
    Elección: "queso",
    "De Donde Vienen": "evento",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Paula Patiño",
    Telefono: "318 7901185",
    Direccion: "calle 99 # 58 - 112",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Paula Urdaneta",
    Telefono: "300 8141441",
    Direccion: "cra 52 # 82 - 202 apto 6a",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Pia Monor",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Roberto Caridi",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Roberto Cuello",
    Telefono: "316 5248764",
    Direccion: "cra 52 # 82 - 161 apto 2b",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Rochy Moreno",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Rodolfo Schmulson",
    Telefono: 3157212121,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Rose Khbeis",
    Telefono: 3015554683,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "zaatar",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Roxana Capella",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Sebastian Otalora",
    Telefono: "315 6684264",
    Direccion: "cra 65 # 81b - 17",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "sanducheria barbaros",
    Correo: "",
  },
  {
    Nombre: "Silvana Maria",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Silvia Aguilera",
    Telefono: "310 6325743",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "caujaral",
    Correo: "",
  },
  {
    Nombre: "Stella Forero",
    Telefono: "310 6320100",
    Direccion: "cra 56 # 80 - 81 apto 8",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Tania Jassit",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Tatiana Charris",
    Telefono: "",
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Traice Biggs",
    Telefono: 3135741437,
    Direccion: "cra 52b # 100 - 240",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "voz a voz",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Valentina Riascos",
    Telefono: 3108978061,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Valerie Hazbun",
    Telefono: 3216652703,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Veronica Duarte",
    Telefono: 3205213683,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Vicky Garcia",
    Telefono: 3157225523,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "amistad",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "VIcky Marquez",
    Telefono: "310 6301785",
    Direccion: "car 56 # 80 - 81 apto 7",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Viri Amiga De Vicky",
    Telefono: 3007572132,
    Direccion: "",
    "Ultima vez hablado": "",
    "Hablar el": "",
    Cumpleanos: "",
    Elección: "",
    "De Donde Vienen": "recomendacion",
    Particularidad: "",
    Correo: "",
  },
  {
    Nombre: "Wicho Jose Escaf",
    Telefono: 3187071815,
    Direccion: "cra 57 # 96 - 38 apt 2c",
    "Ultima vez hablado": "29/Feb/2020",
    "Hablar el": "",
    Cumpleanos: "2020-05-10",
    Elección: "zaatar",
    "De Donde Vienen": "familia",
    Particularidad: "",
    Correo: "",
  },
];
