export const tablesForRendering = [
  {
    date: "2021-12-12T14:11:07-05:00",
    clients: [
      { name: "adriana sáenz", total: 0, status: "darkened" },
      { name: "adriana tribin", total: 0, status: "darkened" },
      { name: "alejandra de la rosa", total: 0, status: "darkened" },
      { name: "alejandro vasquez", total: 0, status: "darkened" },
      { name: "amalin de hazbun", total: 0, status: "darkened" },
      { name: "amparo rueda", total: 0, status: "darkened" },
      { name: "ana maría buitrago", total: 0, status: "darkened" },
      { name: "andrea restrepo", total: 0, status: "darkened" },
      { name: "angela maría salazar", total: 0, status: "darkened" },
      { name: "angélica quiroz", total: 0, status: "darkened" },
      { name: "ara de ochoa", total: 0, status: "darkened" },
      { name: "bernarda florez", total: 0, status: "darkened" },
      { name: "betty de rohenes", total: 0, status: "darkened" },
      { name: "cafe y tapas", total: 0, status: "darkened" },
      { name: "carolina yepes", total: 0, status: "darkened" },
      { name: "cheyenne (sincelejo)", total: 0, status: "darkened" },
      { name: "cielo carbó", total: 0, status: "darkened" },
      { name: "clara marina", total: 0, status: "darkened" },
      {
        name: "clara marina thomasdotter tscherning nilsson",
        total: 0,
        status: "darkened",
      },
      { name: "claudia fuentes", total: 0, status: "darkened" },
      { name: "claudia gome de la e.", total: 0, status: "darkened" },
      { name: "claudia perdomo", total: 0, status: "darkened" },
      { name: "claudia solera", total: 0, status: "darkened" },
      { name: "daniela martinez alvarez", total: 0, status: "darkened" },
      { name: "diana maria ortiz", total: 0, status: "darkened" },
      { name: "diego bustos", total: 0, status: "darkened" },
      { name: "diego mariño", total: 0, status: "darkened" },
      { name: "elvira peynado", total: 0, status: "darkened" },
      { name: "eric pérez (sincelejo)", total: 0, status: "darkened" },
      { name: "erika roca paulsen", total: 0, status: "darkened" },
      { name: "faride rocha", total: 0, status: "darkened" },
      { name: "fithub", total: 0, status: "darkened" },
      { name: "galena del risco", total: 0, status: "darkened" },
      { name: "guillermo escolar", total: 0, status: "darkened" },
      { name: "guillermo solano", total: 0, status: "darkened" },
      { name: "humo", total: 0, status: "darkened" },
      { name: "isabel cristina rodriguez", total: 0, status: "darkened" },
      { name: "ivan garcia", total: 0, status: "darkened" },
      { name: "jaime abello banfi", total: 0, status: "darkened" },
      { name: "jenny pao (sincelejo)", total: 0, status: "darkened" },
      { name: "jessica daccarett", total: 0, status: "darkened" },
      { name: "johanna daccarett", total: 0, status: "darkened" },
      { name: "josefina congote", total: 0, status: "darkened" },
      { name: "juan correa", total: 0, status: "darkened" },
      { name: "juana posse", total: 0, status: "darkened" },
      { name: "judy hazbun", total: 0, status: "darkened" },
      { name: "juliana acevedo", total: 0, status: "darkened" },
      { name: "karol manjarres", total: 0, status: "darkened" },
      { name: "la scarpetta", total: 0, status: "darkened" },
      { name: "lani marenco", total: 0, status: "darkened" },
      { name: "lau pasteleria", total: 0, status: "darkened" },
      { name: "liliana herrera", total: 0, status: "darkened" },
      { name: "lotty", total: 0, status: "darkened" },
      { name: "lucero y willy stewart", total: 0, status: "darkened" },
      { name: "luisa martinez aleman", total: 0, status: "darkened" },
      { name: "luisa porto", total: 0, status: "darkened" },
      { name: "mafe torres", total: 0, status: "darkened" },
      { name: "marcela chain", total: 0, status: "darkened" },
      { name: "margareth serrano", total: 0, status: "darkened" },
      { name: "maria alejandra gutierrez", total: 0, status: "darkened" },
      { name: "maría alejandra kaled", total: 0, status: "darkened" },
      { name: "maría cabello", total: 0, status: "darkened" },
      { name: "maria carolina jacome", total: 0, status: "darkened" },
      { name: "maria cecilia ibarra", total: 0, status: "darkened" },
      {
        name: "maría cristina carbajal de pérez",
        total: 0,
        status: "darkened",
      },
      { name: "maría elena diaz", total: 0, status: "darkened" },
      { name: "maría elvira castro", total: 0, status: "darkened" },
      { name: "maria fernanda garcia", total: 0, status: "darkened" },
      { name: "maria majami", total: 0, status: "darkened" },
      { name: "maria olga escolar", total: 0, status: "darkened" },
      { name: "maria yepes", total: 0, status: "darkened" },
      { name: "mariace arrieta (sincelejo)", total: 0, status: "darkened" },
      { name: "mariana ceballos", total: 0, status: "darkened" },
      { name: "marta luz romero", total: 0, status: "darkened" },
      { name: "martha daza", total: 0, status: "darkened" },
      { name: "mary (sincelejo)", total: 0, status: "darkened" },
      { name: "maya cuello", total: 0, status: "darkened" },
      { name: "mayda george", total: 0, status: "darkened" },
      { name: "milena clavijo", total: 0, status: "darkened" },
      { name: "milena fernandez", total: 0, status: "darkened" },
      { name: "mirella escolar", total: 0, status: "darkened" },
      { name: "myriam tarud", total: 0, status: "darkened" },
      { name: "natalia romero", total: 0, status: "darkened" },
      { name: "natalia salgado", total: 0, status: "darkened" },
      { name: "natalie abuchaibe", total: 0, status: "darkened" },
      { name: "natalie eslait", total: 0, status: "darkened" },
      { name: "nataly cayon", total: 0, status: "darkened" },
      { name: "nestor barrios", total: 0, status: "darkened" },
      { name: "ornella grosso", total: 0, status: "darkened" },
      { name: "pablo bustillo", total: 0, status: "darkened" },
      { name: "paola rodríguez", total: 0, status: "darkened" },
      { name: "patricia maestre", total: 0, status: "darkened" },
      { name: "peggy galvez caney", total: 0, status: "darkened" },
      { name: "picho salgado", total: 0, status: "darkened" },
      { name: "rita bendek", total: 0, status: "darkened" },
      { name: "rosy de vergara", total: 0, status: "darkened" },
      { name: "sandra osman", total: 0, status: "darkened" },
      { name: "sebastian otalora", total: 0, status: "darkened" },
      { name: "silvia aguilera", total: 0, status: "darkened" },
      { name: "silvia perez (sincelejo)", total: 0, status: "darkened" },
      { name: "silvia pinedo", total: 0, status: "darkened" },
      { name: "sofia suarez", total: 0, status: "darkened" },
      { name: "stephanie delgado", total: 0, status: "darkened" },
      { name: "tania renz", total: 0, status: "darkened" },
      { name: "tatiana paola terán correa", total: 0, status: "darkened" },
      { name: "tatiana restrepo", total: 0, status: "darkened" },
      { name: "tita acevedo", total: 0, status: "darkened" },
      { name: "veronica duarte", total: 0, status: "darkened" },
      { name: "vicky garcia", total: 0, status: "darkened" },
      { name: "vicky manotas", total: 0, status: "darkened" },
      { name: "viral brands sas", total: 0, status: "darkened" },
      { name: "wendy garcia", total: 0, status: "darkened" },
      { name: "werner röhricht", total: 0, status: "darkened" },
      { name: "wicho jose escaf", total: 0, status: "darkened" },
      { name: "zaira cervantes", total: 0, status: "darkened" },
    ],
    clientSummary: { absent: 115, new: 0, old: 0, persistent: 0, total: 115 },
    newClients: [],
  },
  {
    date: "2021-12-05T14:11:07-05:00",
    clients: [
      { name: "adriana sáenz", total: 0, status: "darkened" },
      { name: "adriana tribin", total: 0, status: "darkened" },
      { name: "alejandra de la rosa", total: 0, status: "darkened" },
      { name: "alejandro vasquez", total: 0, status: "darkened" },
      {
        name: "amalin de hazbun",
        total: 20000,
        date: "2021-12-06T00:00:00-05:00",
        status: "old",
      },
      { name: "amparo rueda", total: 0, status: "darkened" },
      { name: "ana maría buitrago", total: 0, status: "darkened" },
      { name: "andrea restrepo", total: 0, status: "darkened" },
      { name: "angela maría salazar", total: 0, status: "darkened" },
      { name: "angélica quiroz", total: 0, status: "darkened" },
      { name: "ara de ochoa", total: 0, status: "darkened" },
      { name: "bernarda florez", total: 0, status: "darkened" },
      { name: "betty de rohenes", total: 0, status: "darkened" },
      { name: "cafe y tapas", total: 0, status: "darkened" },
      { name: "carolina yepes", total: 0, status: "darkened" },
      { name: "cheyenne (sincelejo)", total: 0, status: "darkened" },
      { name: "cielo carbó", total: 0, status: "darkened" },
      { name: "clara marina", total: 0, status: "darkened" },
      {
        name: "clara marina thomasdotter tscherning nilsson",
        total: 0,
        status: "darkened",
      },
      { name: "claudia fuentes", total: 0, status: "darkened" },
      { name: "claudia gome de la e.", total: 0, status: "darkened" },
      { name: "claudia perdomo", total: 0, status: "darkened" },
      { name: "claudia solera", total: 0, status: "darkened" },
      {
        name: "daniela martinez alvarez",
        total: 14000,
        date: "2021-12-06T00:00:00-05:00",
        status: "old",
      },
      { name: "diana maria ortiz", total: 0, status: "darkened" },
      { name: "diego bustos", total: 0, status: "darkened" },
      { name: "diego mariño", total: 0, status: "darkened" },
      { name: "elvira peynado", total: 0, status: "darkened" },
      { name: "eric pérez (sincelejo)", total: 0, status: "darkened" },
      { name: "erika roca paulsen", total: 0, status: "darkened" },
      { name: "faride rocha", total: 0, status: "darkened" },
      { name: "fithub", total: 0, status: "darkened" },
      {
        name: "galena del risco",
        total: 25000,
        date: "2021-12-06T00:00:00-05:00",
        status: "persistent",
      },
      { name: "guillermo escolar", total: 0, status: "darkened" },
      {
        name: "guillermo solano",
        total: 30000,
        date: "2021-12-06T00:00:00-05:00",
        status: "old",
      },
      { name: "humo", total: 0, status: "darkened" },
      { name: "isabel cristina rodriguez", total: 0, status: "darkened" },
      { name: "ivan garcia", total: 0, status: "darkened" },
      { name: "jaime abello banfi", total: 0, status: "darkened" },
      { name: "jenny pao (sincelejo)", total: 0, status: "darkened" },
      { name: "jessica daccarett", total: 0, status: "darkened" },
      { name: "johanna daccarett", total: 0, status: "darkened" },
      { name: "josefina congote", total: 0, status: "darkened" },
      { name: "juan correa", total: 0, status: "darkened" },
      {
        name: "juana posse",
        total: 20000,
        date: "2021-12-08T00:00:00-05:00",
        status: "persistent",
      },
      { name: "judy hazbun", total: 0, status: "darkened" },
      { name: "juliana acevedo", total: 0, status: "darkened" },
      { name: "karol manjarres", total: 0, status: "darkened" },
      { name: "la scarpetta", total: 0, status: "darkened" },
      { name: "lani marenco", total: 0, status: "darkened" },
      { name: "lau pasteleria", total: 0, status: "darkened" },
      { name: "liliana herrera", total: 0, status: "darkened" },
      { name: "lotty", total: 0, status: "darkened" },
      {
        name: "lucero y willy stewart",
        total: 12000,
        date: "2021-12-08T00:00:00-05:00",
        status: "persistent",
      },
      { name: "luisa martinez aleman", total: 0, status: "darkened" },
      { name: "luisa porto", total: 0, status: "darkened" },
      { name: "mafe torres", total: 0, status: "darkened" },
      { name: "marcela chain", total: 0, status: "darkened" },
      { name: "margareth serrano", total: 0, status: "darkened" },
      { name: "maria alejandra gutierrez", total: 0, status: "darkened" },
      { name: "maría alejandra kaled", total: 0, status: "darkened" },
      { name: "maría cabello", total: 0, status: "darkened" },
      { name: "maria carolina jacome", total: 0, status: "darkened" },
      { name: "maria cecilia ibarra", total: 0, status: "darkened" },
      {
        name: "maría cristina carbajal de pérez",
        total: 0,
        status: "darkened",
      },
      { name: "maría elena diaz", total: 0, status: "darkened" },
      {
        name: "maría elvira castro",
        total: 20000,
        date: "2021-12-10T00:00:00-05:00",
        status: "persistent",
      },
      { name: "maria fernanda garcia", total: 0, status: "darkened" },
      { name: "maria majami", total: 0, status: "darkened" },
      { name: "maria olga escolar", total: 0, status: "darkened" },
      { name: "maria yepes", total: 0, status: "darkened" },
      { name: "mariace arrieta (sincelejo)", total: 0, status: "darkened" },
      { name: "mariana ceballos", total: 0, status: "darkened" },
      { name: "marta luz romero", total: 0, status: "darkened" },
      { name: "martha daza", total: 0, status: "darkened" },
      { name: "mary (sincelejo)", total: 0, status: "darkened" },
      {
        name: "maya cuello",
        total: 20000,
        date: "2021-12-07T00:00:00-05:00",
        status: "old",
      },
      { name: "mayda george", total: 0, status: "darkened" },
      { name: "milena clavijo", total: 0, status: "darkened" },
      { name: "milena fernandez", total: 0, status: "darkened" },
      { name: "mirella escolar", total: 0, status: "darkened" },
      { name: "myriam tarud", total: 0, status: "darkened" },
      { name: "natalia romero", total: 0, status: "darkened" },
      { name: "natalia salgado", total: 0, status: "darkened" },
      {
        name: "natalie abuchaibe",
        total: 14000,
        date: "2021-12-06T00:00:00-05:00",
        status: "persistent",
      },
      { name: "natalie eslait", total: 0, status: "darkened" },
      { name: "nataly cayon", total: 0, status: "darkened" },
      { name: "nestor barrios", total: 0, status: "darkened" },
      { name: "ornella grosso", total: 0, status: "darkened" },
      { name: "pablo bustillo", total: 0, status: "darkened" },
      { name: "paola rodríguez", total: 0, status: "darkened" },
      {
        name: "patricia maestre",
        total: 35000,
        date: "2021-12-06T00:00:00-05:00",
        status: "old",
      },
      { name: "peggy galvez caney", total: 0, status: "darkened" },
      { name: "picho salgado", total: 0, status: "darkened" },
      { name: "rita bendek", total: 0, status: "darkened" },
      {
        name: "rosy de vergara",
        total: 12000,
        date: "2021-12-10T00:00:00-05:00",
        status: "persistent",
      },
      { name: "sandra osman", total: 0, status: "darkened" },
      { name: "sebastian otalora", total: 0, status: "darkened" },
      {
        name: "silvia aguilera",
        total: 89000,
        date: "2021-12-11T00:00:00-05:00",
        status: "old",
      },
      { name: "silvia perez (sincelejo)", total: 0, status: "darkened" },
      { name: "silvia pinedo", total: 0, status: "darkened" },
      { name: "sofia suarez", total: 0, status: "darkened" },
      { name: "stephanie delgado", total: 0, status: "darkened" },
      { name: "tania renz", total: 0, status: "darkened" },
      { name: "tatiana paola terán correa", total: 0, status: "darkened" },
      {
        name: "tatiana restrepo",
        total: 25000,
        date: "2021-12-09T00:00:00-05:00",
        status: "old",
      },
      { name: "tita acevedo", total: 0, status: "darkened" },
      { name: "veronica duarte", total: 0, status: "darkened" },
      { name: "vicky garcia", total: 0, status: "darkened" },
      { name: "vicky manotas", total: 0, status: "darkened" },
      { name: "viral brands sas", total: 0, status: "darkened" },
      { name: "wendy garcia", total: 0, status: "darkened" },
      { name: "werner röhricht", total: 0, status: "darkened" },
      { name: "wicho jose escaf", total: 0, status: "darkened" },
      { name: "zaira cervantes", total: 0, status: "darkened" },
    ],
    clientSummary: { absent: 102, new: 0, old: 7, persistent: 6, total: 115 },
    newClients: [],
  },
  {
    date: "2021-11-28T14:11:07-05:00",
    clients: [
      {
        name: "adriana sáenz",
        total: 35000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      { name: "adriana tribin", total: 0, status: "darkened" },
      { name: "alejandra de la rosa", total: 0, status: "darkened" },
      {
        name: "alejandro vasquez",
        total: 25000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      { name: "amalin de hazbun", total: 0, status: "darkened" },
      { name: "amparo rueda", total: 0, status: "darkened" },
      {
        name: "ana maría buitrago",
        total: 27000,
        date: "2021-12-01T00:00:00-05:00",
        status: "old",
      },
      { name: "andrea restrepo", total: 0, status: "darkened" },
      { name: "angela maría salazar", total: 0, status: "darkened" },
      {
        name: "angélica quiroz",
        total: 27000,
        date: "2021-12-03T00:00:00-05:00",
        status: "new",
      },
      {
        name: "ara de ochoa",
        total: 44000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      {
        name: "bernarda florez",
        total: 50000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      { name: "betty de rohenes", total: 0, status: "darkened" },
      {
        name: "cafe y tapas",
        total: 57000,
        date: "2021-12-04T00:00:00-05:00",
        status: "persistent",
      },
      { name: "carolina yepes", total: 0, status: "darkened" },
      {
        name: "cheyenne (sincelejo)",
        total: 47000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      { name: "cielo carbó", total: 0, status: "darkened" },
      { name: "clara marina", total: 0, status: "darkened" },
      {
        name: "clara marina thomasdotter tscherning nilsson",
        total: 35000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      { name: "claudia fuentes", total: 0, status: "darkened" },
      {
        name: "claudia gome de la e.",
        total: 30000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      {
        name: "claudia perdomo",
        total: 24000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      {
        name: "claudia solera",
        total: 74000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      { name: "daniela martinez alvarez", total: 0, status: "darkened" },
      { name: "diana maria ortiz", total: 0, status: "darkened" },
      { name: "diego bustos", total: 0, status: "darkened" },
      { name: "diego mariño", total: 0, status: "darkened" },
      { name: "elvira peynado", total: 0, status: "darkened" },
      {
        name: "eric pérez (sincelejo)",
        total: 57000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      {
        name: "erika roca paulsen",
        total: 41000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      { name: "faride rocha", total: 0, status: "darkened" },
      {
        name: "fithub",
        total: 1159000,
        date: "2021-11-30T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "galena del risco",
        total: 25000,
        date: "2021-11-29T00:00:00-05:00",
        status: "persistent",
      },
      { name: "guillermo escolar", total: 0, status: "darkened" },
      { name: "guillermo solano", total: 0, status: "darkened" },
      {
        name: "humo",
        total: 149000,
        date: "2021-12-02T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "isabel cristina rodriguez",
        total: 49000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "ivan garcia",
        total: 27000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "jaime abello banfi",
        total: 60000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "jenny pao (sincelejo)",
        total: 27000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      {
        name: "jessica daccarett",
        total: 23000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      {
        name: "johanna daccarett",
        total: 23000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      { name: "josefina congote", total: 0, status: "darkened" },
      { name: "juan correa", total: 0, status: "darkened" },
      {
        name: "juana posse",
        total: 20000,
        date: "2021-12-01T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "judy hazbun",
        total: 120000,
        date: "2021-11-30T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "juliana acevedo",
        total: 21000,
        date: "2021-12-03T00:00:00-05:00",
        status: "new",
      },
      { name: "karol manjarres", total: 0, status: "darkened" },
      { name: "la scarpetta", total: 0, status: "darkened" },
      { name: "lani marenco", total: 0, status: "darkened" },
      {
        name: "lau pasteleria",
        total: 41000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "liliana herrera",
        total: 46000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      {
        name: "lotty",
        total: 25000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "lucero y willy stewart",
        total: 12000,
        date: "2021-12-01T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "luisa martinez aleman",
        total: 49000,
        date: "2021-12-02T00:00:00-05:00",
        status: "new",
      },
      {
        name: "luisa porto",
        total: 30000,
        date: "2021-12-03T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "mafe torres",
        total: 21000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "marcela chain",
        total: 27000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      { name: "margareth serrano", total: 0, status: "darkened" },
      { name: "maria alejandra gutierrez", total: 0, status: "darkened" },
      { name: "maría alejandra kaled", total: 0, status: "darkened" },
      {
        name: "maría cabello",
        total: 23000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maria carolina jacome",
        total: 21000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      { name: "maria cecilia ibarra", total: 0, status: "darkened" },
      {
        name: "maría cristina carbajal de pérez",
        total: 64000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maría elena diaz",
        total: 70000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maría elvira castro",
        total: 20000,
        date: "2021-12-03T00:00:00-05:00",
        status: "persistent",
      },
      {
        name: "maria fernanda garcia",
        total: 41000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maria majami",
        total: 39000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maria olga escolar",
        total: 36000,
        date: "2021-12-01T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maria yepes",
        total: 21000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      {
        name: "mariace arrieta (sincelejo)",
        total: 27000,
        date: "2021-11-30T00:00:00-05:00",
        status: "new",
      },
      { name: "mariana ceballos", total: 0, status: "darkened" },
      {
        name: "marta luz romero",
        total: 30000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      { name: "martha daza", total: 0, status: "darkened" },
      {
        name: "mary (sincelejo)",
        total: 20000,
        date: "2021-11-30T00:00:00-05:00",
        status: "new",
      },
      { name: "maya cuello", total: 0, status: "darkened" },
      {
        name: "mayda george",
        total: 59000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "milena clavijo",
        total: 41000,
        date: "2021-12-01T00:00:00-05:00",
        status: "old",
      },
      {
        name: "milena fernandez",
        total: 35000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      {
        name: "mirella escolar",
        total: 60000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      { name: "myriam tarud", total: 0, status: "darkened" },
      {
        name: "natalia romero",
        total: 40000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      { name: "natalia salgado", total: 0, status: "darkened" },
      {
        name: "natalie abuchaibe",
        total: 14000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      { name: "natalie eslait", total: 0, status: "darkened" },
      { name: "nataly cayon", total: 0, status: "darkened" },
      {
        name: "nestor barrios",
        total: 27000,
        date: "2021-12-02T00:00:00-05:00",
        status: "old",
      },
      {
        name: "ornella grosso",
        total: 35000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      { name: "pablo bustillo", total: 0, status: "darkened" },
      { name: "paola rodríguez", total: 0, status: "darkened" },
      { name: "patricia maestre", total: 0, status: "darkened" },
      {
        name: "peggy galvez caney",
        total: 27000,
        date: "2021-12-01T00:00:00-05:00",
        status: "persistent",
      },
      { name: "picho salgado", total: 0, status: "darkened" },
      {
        name: "rita bendek",
        total: 60000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      {
        name: "rosy de vergara",
        total: 20000,
        date: "2021-12-03T00:00:00-05:00",
        status: "persistent",
      },
      { name: "sandra osman", total: 0, status: "darkened" },
      {
        name: "sebastian otalora",
        total: 41000,
        date: "2021-12-04T00:00:00-05:00",
        status: "persistent",
      },
      { name: "silvia aguilera", total: 0, status: "darkened" },
      {
        name: "silvia perez (sincelejo)",
        total: 62000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      { name: "silvia pinedo", total: 0, status: "darkened" },
      { name: "sofia suarez", total: 0, status: "darkened" },
      { name: "stephanie delgado", total: 0, status: "darkened" },
      {
        name: "tania renz",
        total: 42000,
        date: "2021-12-03T00:00:00-05:00",
        status: "new",
      },
      {
        name: "tatiana paola terán correa",
        total: 35000,
        date: "2021-12-01T00:00:00-05:00",
        status: "old",
      },
      { name: "tatiana restrepo", total: 0, status: "darkened" },
      {
        name: "tita acevedo",
        total: 35000,
        date: "2021-12-04T00:00:00-05:00",
        status: "old",
      },
      {
        name: "veronica duarte",
        total: 55000,
        date: "2021-11-29T00:00:00-05:00",
        status: "old",
      },
      { name: "vicky garcia", total: 0, status: "darkened" },
      { name: "vicky manotas", total: 0, status: "darkened" },
      { name: "viral brands sas", total: 0, status: "darkened" },
      {
        name: "wendy garcia",
        total: 44000,
        date: "2021-11-30T00:00:00-05:00",
        status: "old",
      },
      { name: "werner röhricht", total: 0, status: "darkened" },
      {
        name: "wicho jose escaf",
        total: 47000,
        date: "2021-12-03T00:00:00-05:00",
        status: "old",
      },
      { name: "zaira cervantes", total: 0, status: "darkened" },
    ],
    clientSummary: { absent: 50, new: 6, old: 47, persistent: 12, total: 115 },
    newClients: [
      "angélica quiroz",
      "juliana acevedo",
      "luisa martinez aleman",
      "mariace arrieta (sincelejo)",
      "mary (sincelejo)",
      "tania renz",
    ],
  },
  {
    date: "2021-11-21T14:11:07-05:00",
    clients: [
      { name: "adriana sáenz", total: 0, status: "darkened" },
      {
        name: "adriana tribin",
        total: 49000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      {
        name: "alejandra de la rosa",
        total: 61000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      { name: "alejandro vasquez", total: 0, status: "darkened" },
      {
        name: "amalin de hazbun",
        total: 30000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "amparo rueda",
        total: 9000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      { name: "ana maría buitrago", total: 0, status: "darkened" },
      {
        name: "andrea restrepo",
        total: 20000,
        date: "2021-11-26T00:00:00-05:00",
        status: "new",
      },
      {
        name: "angela maría salazar",
        total: 22000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      { name: "angélica quiroz", total: 0, status: "darkened" },
      { name: "ara de ochoa", total: 0, status: "darkened" },
      { name: "bernarda florez", total: 0, status: "darkened" },
      {
        name: "betty de rohenes",
        total: 27000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      {
        name: "cafe y tapas",
        total: 45000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "carolina yepes",
        total: 10000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      { name: "cheyenne (sincelejo)", total: 0, status: "darkened" },
      {
        name: "cielo carbó",
        total: 25000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      {
        name: "clara marina",
        total: 35000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      {
        name: "clara marina thomasdotter tscherning nilsson",
        total: 0,
        status: "darkened",
      },
      {
        name: "claudia fuentes",
        total: 15000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      { name: "claudia gome de la e.", total: 0, status: "darkened" },
      { name: "claudia perdomo", total: 0, status: "darkened" },
      { name: "claudia solera", total: 0, status: "darkened" },
      {
        name: "daniela martinez alvarez",
        total: 14000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "diana maria ortiz",
        total: 48000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "diego bustos",
        total: 32000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "diego mariño",
        total: 22000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "elvira peynado",
        total: 44000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      { name: "eric pérez (sincelejo)", total: 0, status: "darkened" },
      { name: "erika roca paulsen", total: 0, status: "darkened" },
      {
        name: "faride rocha",
        total: 41000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "fithub",
        total: 1356500,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      {
        name: "galena del risco",
        total: 25000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "guillermo escolar",
        total: 21000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      {
        name: "guillermo solano",
        total: 30000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "humo",
        total: 149000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      { name: "isabel cristina rodriguez", total: 0, status: "darkened" },
      { name: "ivan garcia", total: 0, status: "darkened" },
      { name: "jaime abello banfi", total: 0, status: "darkened" },
      { name: "jenny pao (sincelejo)", total: 0, status: "darkened" },
      { name: "jessica daccarett", total: 0, status: "darkened" },
      { name: "johanna daccarett", total: 0, status: "darkened" },
      {
        name: "josefina congote",
        total: 49000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "juan correa",
        total: 35000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      {
        name: "juana posse",
        total: 22000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      {
        name: "judy hazbun",
        total: 13000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      { name: "juliana acevedo", total: 0, status: "darkened" },
      {
        name: "karol manjarres",
        total: 35000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      {
        name: "la scarpetta",
        total: 66000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      {
        name: "lani marenco",
        total: 46000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      { name: "lau pasteleria", total: 0, status: "darkened" },
      { name: "liliana herrera", total: 0, status: "darkened" },
      { name: "lotty", total: 0, status: "darkened" },
      {
        name: "lucero y willy stewart",
        total: 12000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      { name: "luisa martinez aleman", total: 0, status: "darkened" },
      {
        name: "luisa porto",
        total: 48000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      { name: "mafe torres", total: 0, status: "darkened" },
      { name: "marcela chain", total: 0, status: "darkened" },
      {
        name: "margareth serrano",
        total: 29000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maria alejandra gutierrez",
        total: 23000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maría alejandra kaled",
        total: 26000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      { name: "maría cabello", total: 0, status: "darkened" },
      { name: "maria carolina jacome", total: 0, status: "darkened" },
      {
        name: "maria cecilia ibarra",
        total: 53000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      {
        name: "maría cristina carbajal de pérez",
        total: 0,
        status: "darkened",
      },
      { name: "maría elena diaz", total: 0, status: "darkened" },
      {
        name: "maría elvira castro",
        total: 20000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      { name: "maria fernanda garcia", total: 0, status: "darkened" },
      { name: "maria majami", total: 0, status: "darkened" },
      { name: "maria olga escolar", total: 0, status: "darkened" },
      { name: "maria yepes", total: 0, status: "darkened" },
      { name: "mariace arrieta (sincelejo)", total: 0, status: "darkened" },
      {
        name: "mariana ceballos",
        total: 62000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      { name: "marta luz romero", total: 0, status: "darkened" },
      {
        name: "martha daza",
        total: 62000,
        date: "2021-11-26T00:00:00-05:00",
        status: "new",
      },
      { name: "mary (sincelejo)", total: 0, status: "darkened" },
      {
        name: "maya cuello",
        total: 20000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      { name: "mayda george", total: 0, status: "darkened" },
      { name: "milena clavijo", total: 0, status: "darkened" },
      { name: "milena fernandez", total: 0, status: "darkened" },
      { name: "mirella escolar", total: 0, status: "darkened" },
      {
        name: "myriam tarud",
        total: 25000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      { name: "natalia romero", total: 0, status: "darkened" },
      {
        name: "natalia salgado",
        total: 31000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      {
        name: "natalie abuchaibe",
        total: 0,
        date: "2021-11-22T00:00:00-05:00",
        status: "darkened",
      },
      {
        name: "natalie eslait",
        total: 49000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "nataly cayon",
        total: 60000,
        date: "2021-11-24T00:00:00-05:00",
        status: "new",
      },
      { name: "nestor barrios", total: 0, status: "darkened" },
      { name: "ornella grosso", total: 0, status: "darkened" },
      {
        name: "pablo bustillo",
        total: 0,
        date: "2021-11-22T00:00:00-05:00",
        status: "darkened",
      },
      {
        name: "paola rodríguez",
        total: 37000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      { name: "patricia maestre", total: 0, status: "darkened" },
      {
        name: "peggy galvez caney",
        total: 27000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "picho salgado",
        total: 22000,
        date: "2021-11-24T00:00:00-05:00",
        status: "old",
      },
      { name: "rita bendek", total: 0, status: "darkened" },
      {
        name: "rosy de vergara",
        total: 32000,
        date: "2021-11-26T00:00:00-05:00",
        status: "old",
      },
      {
        name: "sandra osman",
        total: 25000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      {
        name: "sebastian otalora",
        total: 41000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      {
        name: "silvia aguilera",
        total: 89000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      { name: "silvia perez (sincelejo)", total: 0, status: "darkened" },
      {
        name: "silvia pinedo",
        total: 15000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      {
        name: "sofia suarez",
        total: 30000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      {
        name: "stephanie delgado",
        total: 66000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      { name: "tania renz", total: 0, status: "darkened" },
      { name: "tatiana paola terán correa", total: 0, status: "darkened" },
      {
        name: "tatiana restrepo",
        total: 40000,
        date: "2021-11-25T00:00:00-05:00",
        status: "old",
      },
      { name: "tita acevedo", total: 0, status: "darkened" },
      { name: "veronica duarte", total: 0, status: "darkened" },
      {
        name: "vicky garcia",
        total: 49000,
        date: "2021-11-23T00:00:00-05:00",
        status: "old",
      },
      {
        name: "vicky manotas",
        total: 44000,
        date: "2021-11-22T00:00:00-05:00",
        status: "old",
      },
      {
        name: "viral brands sas",
        total: 55000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      { name: "wendy garcia", total: 0, status: "darkened" },
      {
        name: "werner röhricht",
        total: 177500,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
      { name: "wicho jose escaf", total: 0, status: "darkened" },
      {
        name: "zaira cervantes",
        total: 29000,
        date: "2021-11-27T00:00:00-05:00",
        status: "old",
      },
    ],
    clientSummary: { absent: 55, new: 3, old: 57, persistent: 0, total: 115 },
    newClients: ["andrea restrepo", "martha daza", "nataly cayon"],
  },
];
