export const tablesBeforeFormatting = [
  [
    "guillermo solano",
    "galena del risco",
    "daniela martinez alvarez",
    "natalie abuchaibe",
    "amalin de hazbun",
    "judy hazbun",
    "diego mariño",
    "pablo bustillo",
    "vicky manotas",
    "margareth serrano",
    "peggy galvez caney",
    "paola rodríguez",
    "maya cuello",
    "juana posse",
    "adriana tribin",
    "fithub",
    "myriam tarud",
    "vicky garcia",
    "amparo rueda",
    "stephanie delgado",
    "sebastian otalora",
    "lucero y willy stewart",
    "stephanie delgado",
    "carolina yepes",
    "karol manjarres",
    "la scarpetta",
    "clara marina",
    "alejandra de la rosa",
    "juan correa",
    "maria cecilia ibarra",
    "betty de rohenes",
    "luisa porto",
    "nataly cayon",
    "fithub",
    "picho salgado",
    "cielo carbó",
    "mariana ceballos",
    "fithub",
    "natalia salgado",
    "humo",
    "sofia suarez",
    "tatiana restrepo",
    "angela maría salazar",
    "rosy de vergara",
    "maría elvira castro",
    "elvira peynado",
    "andrea restrepo",
    "martha daza",
    "josefina congote",
    "maría alejandra kaled",
    "diana maria ortiz",
    "claudia fuentes",
    "cafe y tapas",
    "maria alejandra gutierrez",
    "natalie eslait",
    "diego bustos",
    "rosy de vergara",
    "faride rocha",
    "pablo bustillo",
    "silvia aguilera",
    "fithub",
    "lani marenco",
    "werner röhricht",
    "zaira cervantes",
    "sandra osman",
    "guillermo escolar",
    "silvia pinedo",
    "viral brands sas",
  ],
  [
    "galena del risco",
    "natalie abuchaibe",
    "erika roca paulsen",
    "veronica duarte",
    "rita bendek",
    "maria yepes",
    "claudia solera",
    "natalia romero",
    "fithub",
    "fithub",
    "judy hazbun",
    "ornella grosso",
    "wendy garcia",
    "maría elena diaz",
    "cheyenne (sincelejo)",
    "claudia perdomo",
    "jenny pao (sincelejo)",
    "silvia perez (sincelejo)",
    "eric pérez (sincelejo)",
    "mariace arrieta (sincelejo)",
    "mary (sincelejo)",
    "tatiana paola terán correa",
    "lucero y willy stewart",
    "juana posse",
    "ana maría buitrago",
    "milena clavijo",
    "maria olga escolar",
    "peggy galvez caney",
    "alejandro vasquez",
    "lau pasteleria",
    "jaime abello banfi",
    "ivan garcia",
    "nestor barrios",
    "maría cabello",
    "lotty",
    "mafe torres",
    "mayda george",
    "isabel cristina rodriguez",
    "luisa martinez aleman",
    "fithub",
    "humo",
    "ara de ochoa",
    "rosy de vergara",
    "maría elvira castro",
    "wicho jose escaf",
    "marcela chain",
    "jessica daccarett",
    "marta luz romero",
    "juliana acevedo",
    "adriana sáenz",
    "maria carolina jacome",
    "maria fernanda garcia",
    "milena fernandez",
    "maría elena diaz",
    "maria majami",
    "luisa porto",
    "tania renz",
    "fithub",
    "angélica quiroz",
    "fithub",
    "bernarda florez",
    "fithub",
    "mirella escolar",
    "maría cristina carbajal de pérez",
    "sebastian otalora",
    "claudia gome de la e.",
    "cafe y tapas",
    "liliana herrera",
    "johanna daccarett",
    "clara marina thomasdotter tscherning nilsson",
    "tita acevedo",
  ],
  [
    "guillermo solano",
    "daniela martinez alvarez",
    "natalie abuchaibe",
    "amalin de hazbun",
    "patricia maestre",
    "arturo rincon",
    "cindy camargo barreto",
    "karin alvarez",
    "maria olga escolar",
    "maría cristina carbajal de pérez",
    "laura llanos",
    "neris higuita",
    "lucero y willy stewart",
    "galena del risco",
    "juana posse",
    "tres fuegos",
    "silvana paternostro",
    "fithub",
    "margarita ceballos",
    "sandra osman",
    "humo",
    "sofia suarez",
    "mafe torres",
    "silvana escaf",
    "viral brands sas",
    "diego bustos",
    "josefina congote",
    "rita bendek",
    "heidy leal",
    "viri amiga de vicky",
    "orlando malkun",
    "paula patiño",
    "felipe echeverri",
    "andres vergara",
    "carlos alberto salgado",
    "catalina diaz",
    "peggy galvez caney",
    "tatiana restrepo",
    "karen jassir",
    "esteban salgado",
    "aniluz pereira",
    "jorge mario suarez",
    "carolina coronado",
    "ana elena vega consuegra",
    "andrea zambrano",
    "foodology",
    "rosy de vergara",
    "maría elvira castro",
    "lucia abdala",
    "humo",
    "maría camila de la hoz",
    "diego mariño",
    "mariana ceballos",
    "aileen camargo diaz",
    "cielo carbó",
    "angela maría salazar",
    "martha daza",
    "cheyenne (sincelejo)",
    "diandra iguaran",
    "picho salgado",
    "alexander montalvo",
    "giovanni felizzola",
    "karen adrians",
    "fithub",
    "silvia aguilera",
    "fithub",
    "laura diaz",
    "giselle dugand",
    "gustavo quilla bike",
    "mónica gontovnik",
    "la scarpetta",
    "sonia escaf",
    "viral brands sas",
    "ornella grosso",
    "paola acuña",
  ],
  ["laura polo", "jessica pimiento", "sandra osman", "fernando garcia"],
];
